config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
  end

  get "/profile" => "users#show", :as => "profile"
  patch "/profile" => "users#update", :as => "update_profile"

  get "/ask_alives" => "ask_alives#confirm", :as => "ask_alive"

  get "/admin" => "ask_alives#ask_admin", :as => "admin"
  get "/admin/check_facebook" => "ask_alives#check_facebook", :as => "check_facebook"
  get "/admin/send_theword" => "ask_alives#send_theword", :as => "send_theword"
  get "/admin/send_ask_mail" => "ask_alives#send_ask_mail", :as => "send_ask_mail"

  root 'messages#index'

  resources :messages
  resources :contacts

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :receivers, :dependent => :destroy
  has_many :contacts, :through => :receivers

  validates_presence_of :content
  before_save :draft_or_final

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :audio
  validates_attachment_content_type :audio, :content_type => /\Aaudio\/.*\Z/


  has_attached_file :video
  validates_attachment_content_type :video, :content_type => /\Avideo\/.*\Z/

  def create_message_notify
    UserMailer.notify_comment(self.user, self).deliver_later!
  end

  protected

  def draft_or_final
    if self.status == "final" && self.receivers.empty?
      self.status = "draft"
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_my_message, :only => [:edit, :update, :destroy]

  def index
    @messages = current_user.messages.includes( :receivers => :contact ).order("id DESC")
    @message = Message.new
    @contacts = current_user.contacts.includes( :receivers ).only_check_alive

    @all_contacts = current_user.contacts.includes(:receivers)

    @contact = Contact.new
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(multi_file_types_params)
    @message.user = current_user
    if params["commit"] == "草稿" || @message.receivers.first == nil
      @message.status = "draft"
    end
    if @message.save
      flash[:notice] = "message was successfully created!!"
      @message.create_message_notify
      redirect_to messages_path
    else
      redirect_to :back
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  def edit
  end

  def update
    if params["commit"] == "草稿"
      @message.status = "draft"
    else
      @message.status = "final"
    end

    respond_to do |format|
      if @message.update(message_params)
        format.html{ redirect_to root_url }
        format.js{ render :action => "index" }
      else
        format.html { render :action => "edit" }
        format.js
      end
    end
  end

  def destroy
    @message.destroy

    respond_to do |format|
      format.html{ redirect_to root_url }
      format.js
    end
  end

  private

  def message_params
    params[:message][:contact_ids] = Array(params[:message][:contact_ids]).uniq

    params.require(:message).permit(:content, :delivery_date, :user_id, :status, :image, :audio, :video, :contact_ids => [])
  end

  def set_my_message
    @message = current_user.messages.find(params[:id])
  end

  def multi_file_types_params

    params[:message][:contact_ids] = Array(params[:message][:contact_ids]).uniq

    if params[:message][:foo]
      if params[:message][:foo].content_type.include? 'image'
        params[:message][:image] = params[:message][:foo]
      elsif params[:message][:foo].content_type.include? 'video'
        params[:message][:video] = params[:message][:foo]
      elsif params[:message][:foo].content_type.include? 'audio'
        params[:message][:audio] = params[:message][:foo]
      end
    end

    params[:message].delete :foo
    params.require(:message).permit(:content, :delivery_date, :user_id, :status, :image, :audio, :video, :contact_ids => [])
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_edit.html.erb
<div class="message-new mge-show clearfix mge-edit-form", id="edit-mge-<%= message.id %>">
  <legend>修改遺言</legend>
  <%= form_for message, :url => message_path(message) do |m| %>

    <%= select_tag "message[contact_ids]", grouped_options_for_select(options_for_receiver(@all_contacts), m.object.contact_ids ), :multiple => true, :class=> "receivers-select receivers-s2", :placeholder => "收訊人: 媽媽" %>
    <button type="button" class="btn btn-default receiver-add" data-toggle="modal" data-target="#myModal" data-tooltip="hello world">新增收訊人</button>

    <%= m.text_area :content, :class=> "form-control message-input-area", :rows => 5, :value=> message.content %>
    <div class="form-group">
      上傳檔案：
      <%= m.file_field :image, class: 'inline-block' %>
      <%= check_box_tag "destroy_photo", "1" %> 刪除檔案
    </div>
    指定傳送日期：

    <div class='input-group date'>
      <%= m.text_field :delivery_date, :class => 'form-control datepicker',default: DateTime.current %>
      <span class="input-group-addon look-outline-red">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
    <div class="pull-right">
      <%= m.submit "草稿", :class => 'btn btn-primary', :status => "draft" %>
      <%= m.submit "完成", :class => 'btn btn-primary', :status => "OK" %>
    </div>
  <% end %>
</div>

app/views/messages/_edit_ajax.html.erb
<div class="col-md-3"></div>
<div class="col-md-6">

  <%= form_for @message, :url => message_path  do |m| %>


  <%= render :partial => "edit", :locals => { :message => @message } %>

      <%= m.submit "取消", :class => 'btn btn-danger', :status => "draft", :data =>{:confirm =>'r u sure?'} %>
      <%= m.submit "確定更新", :class => 'btn btn-primary'%>
  <% end %>
</div>

app/views/messages/_new.html.erb
<div class="message-new mge-show clearfix">
  <%= form_for @message, :url => messages_path do |m| %>

    <%= select_tag "message[contact_ids]", grouped_options_for_select(options_for_receiver(@all_contacts)), :multiple => true, :class=> "receivers-select receivers-s2", :placeholder => "收訊人: 媽媽" %>

    <button type="button" class="btn btn-primary receiver-add" data-toggle="modal" data-target="#myModal" data-tooltip="hello world">＋ 新增收訊人</button>
    <%= m.text_area :content, :class=> "form-control message-input-area", :rows => 5, placeholder: :"媽, 謝謝妳給我這一生,我愛妳 ^^" %>
    <br>
    <div class="form-group">
      可上傳照片及影音檔案<%= m.file_field :foo, class: 'inline-block' %>
    </div>
    指定傳送日期：

    <div class='input-group date'>
      <%= m.text_field :delivery_date, :class => 'form-control datepicker',default: DateTime.current %>
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
      </span>
    </div>
    <div class="pull-right">
      <%= m.submit "草稿", :class => 'btn btn-primary', :status => "draft" %>
      <%= m.submit "完成", :class => 'btn btn-primary', :status => "final" %>
    </div>
  <% end %>
</div>

<!-- 新增收訊人 Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">新增收訊人</h4>
      </div>
      <div class="modal-body">
        <%= form_for @contact, :url => contacts_path do |f|%>
        <div class="form-group">
          <%= f.label "聯絡人姓名" %> <br>
          <%= f.text_field :name, :value => @contact.name, :class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label "他是你的...(關係)" %> <br>
          <%= f.text_field :relationship, :value => @contact.relationship, :class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label "行動電話" %> <br>
          <%= f.text_field :phone, :value => @contact.phone, :class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label "備用電話" %> <br>
          <%= f.text_field :home_phone, :value => @contact.home_phone, :class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label "Email" %> <br>
          <%= f.text_field :email, :value => @contact.email, :type => "email", :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label "地址" %> <br>
          <%= f.text_field :address, :value => @contact.address, :class => "form-control"  %>
        </div>
          <%= f.hidden_field :check_alive, :value => false %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">取消新增</button>
        <%= f.submit '確定新增', :class => "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/_show.html.erb
<div class="mge-show">

  <div class="bg-pic">

    <div class="bg-text1">
      <div class="draft-style"><%= "草稿" if m.status == "draft" %></div>
      <div class="pull-right">
        <%= m.created_at.to_s(:short) %>
        <!-- Single button -->
        <div class="btn-group">
          <button type="button" class="btn btn-warning dropdown-toggle " data-toggle="dropdown" aria-expanded="false">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#" class="editmessage" data-id="<%= m.id %>">修改遺言</a></li>
            <li><%= link_to '刪除遺言', message_path(m), :data =>{:confirm => "確定要刪除這則遺言?"}, :method => :delete, :remote => true %></li>
          </ul>
        </div>
      </div>
      給：
      <% m.contacts.each_with_index do |contact, index| %>
      <li class="receiver-name receiver-<%= index %>"><%= contact.name %></li>
      <% end %>
      <p>指定傳送日期: <%= m.delivery_date.to_s %></p>
    </div>
  </div>

  <div class="mge-content">

    <% if m.image_file_name %>
      <%= image_tag m.image.url(:medium) %>
    <% end %>

    <% if m.audio.exists? %>
       <%= audio_tag(m.audio.url, :controls => true) %>
    <% end %>

    <% if m.video.exists? %>
       <%= video_tag(m.video.url, :controls => true, :width => 400 ) %>
    <% end %>

    <p><%=simple_format m.content %></p>
  </div>
</div>

app/views/messages/create.js.erb
$("#mge-<%= @messages.id %> ul").append("<li id='<%= @comment.id %>'><%= j(render :partial => "comment", :locals => { :photo => @photo, :comment => @comment } ) %></li>");
// $("#photo-comments-<%= @photo.id %> ul").append("<li><%= j(render :partial => "comment", :locals => { :photo => @photo, :comment => @comment } ) %></li>");
$("#new_comment").trigger("reset");

app/views/messages/destroy.js.erb
$("#mge-<%= @message.id %>").remove();

app/views/messages/edit.js.erb
$("#mge-<%= @message.id %>").prepend("<%= j(render :partial => "edit_ajax", :locals => { :content => @message.content } ) %>");
$("#new_comment").trigger("reset");

app/views/messages/index.html.erb
<div class="container">

  <!-- 遺言範例 -->
    <div class="theword-sample col-md-3">
      <div class="title-bg">
        <div class="title-content">看看遺言範例
      </div>
    </div>

      <div class="example-content text-center">
        <p>給親愛的媽媽:</p>
        <p>  這是我在前往亞馬遜河探險前所寫下的，當妳看到這封訊息時，表示我已經不在了... 兒子不孝，沒能好好奉養妳，還讓妳傷心。但此行是我一大心願，雖然危險卻非去不可，能長眠於此，也是我最好的歸宿了~!!</p>
      <legend></legend>
        <a href="#" data-toggle="modal" data-target=".bs-example-modal-sm">
        <%= image_tag "sky_theword.jpg", :class=> "theword_sample" %>
        </a>
        <!-- javascript -->
          <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <%= image_tag "sky_theword.jpg",:width=>"200%",:higth => "200%", :class=> "theword_sample" %>
              </div>
            </div>
          </div>
      </div>
    </div>

  <div class="col-md-6">
    <!-- Message new -->
    <div class="new-message-bg">
      <div class="title-content">
        新增一則遺言
      </div>
    </div>
    <%= render :partial => "new", :locals => { :message => @message } %>
    <p></p>
    <% @messages.each do |m| %>
      <!-- Message show -->

      <div class="mge-show-id" id="mge-<%= m.id %>" data-id="<%= m.id %>">
        <%= render :partial => "show", :locals => { :m => m } %>
      </div>
      <!-- message edit -->
      <%= render :partial => "edit", :locals => { :message => m } %>


    <% end %>
  </div>

  <!-- Receiver List -->
  <div class="col-md-3 ">

    <div class="col-xs-12">
      <div class="receiver-bg">
        <div class="receiver-bg-title title-content-xs">收訊人
        </div>
      </div>
    </div>

    <div class="receiver-bg">
      <div class="receiver-bg">
            <div class="receiver-bg-title title-content">收訊人
        </div>
      </div>
    </div>

    <div class="receiver-list">
      <p>您目前留了遺言給以下對象</p>
      <ul>
        <% @contacts.each do |c| %>
          <p><%= c.name if c.receivers.first %></p>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- Contact List -->
  <div class="col-md-3">
    <div class="contact-bg">
      <div class="title-content">
        聯絡人
      </div>
    </div>
    <div class="contact-list">
    <p>當我們無法與您聯繫時，將聯絡以下對象</p>
    <% @contacts.each do |c| %>
      <%= link_to c.name, c, :class => "col-md-10" %>
      <%= link_to "x", c, :method => :delete, :data =>{:confirm => "確定要刪除此收訊人?"} , :class => "col-md-2 contact-delete" %>
    <% end %>

    <%= link_to '+', new_contact_path, :class => 'btn btn-default btn-add-contact' %>
    </div>
    <!-- FB Page -->
    <div id="fb-root" class="theword-sample col-md-3">
      <div class="fb-page" data-href="https://www.facebook.com/pages/%E7%95%99%E4%B8%8B%E9%81%BA%E8%A8%80%E7%95%99%E4%B8%8B%E6%84%9B/1564354127160181?fref=ts" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/pages/%E7%95%99%E4%B8%8B%E9%81%BA%E8%A8%80%E7%95%99%E4%B8%8B%E6%84%9B/1564354127160181?fref=ts"><a href="https://www.facebook.com/pages/%E7%95%99%E4%B8%8B%E9%81%BA%E8%A8%80%E7%95%99%E4%B8%8B%E6%84%9B/1564354127160181?fref=ts">留下遺言，留下愛</a></blockquote></div></div>
    </div>
  </div>
</div>

<script>
  //$(".editmessage").first().closest(".mge-show").find(".mge-edit-form").toggle()
  $(".mge-edit-form").hide();
  $(".editmessage").on("click", function(event) {
    event.preventDefault();

    id = $(this).data("id");
    //console.log("get data-id="+id);

    $("#mge-"+id).toggle();
    $("#edit-mge-"+id).toggle();
  });

  $('.datepicker').datepicker({
     format: "yyyy/mm/dd"
  });

  $(".receivers-select").select2();

  $('#myModal').on('shown.bs.modal', function () {
    $('#myInput').focus()
  })

</script>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.3&appId=882105101852973";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>