config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
  end

  get "/profile" => "users#show", :as => "profile"
  patch "/profile" => "users#update", :as => "update_profile"

  get "/ask_alives" => "ask_alives#confirm", :as => "ask_alive"

  get "/admin" => "ask_alives#ask_admin", :as => "admin"
  get "/admin/check_facebook" => "ask_alives#check_facebook", :as => "check_facebook"
  get "/admin/send_theword" => "ask_alives#send_theword", :as => "send_theword"
  get "/admin/send_ask_mail" => "ask_alives#send_ask_mail", :as => "send_ask_mail"

  root 'messages#index'

  resources :messages
  resources :contacts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :contacts, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  has_many :ask_alives

  #validates_inclusion_of :status, :in => ["alive", "dead", "sent"]

  def send_theword
    self.messages.where( :status => "final").each do |m|
      m.receivers.each do |r|
        UserMailer.send_theword(m,r).deliver_now!
      end
    end
    self.status = "sent"
    self.save
  end

  def check_facebook!
    #conn = Faraday.new(:url => 'https://graph.facebook.com/me')
    #response1 = conn.get "/me", { :access_token => self.fb_token }
    #data1 = JSON.parse(response.body)

    conn = Faraday.new(:url => 'https://graph.facebook.com')
    response2 = conn.get "/#{self.uid}/posts", { :access_token => self.fb_token }
    data2 = JSON.parse(response2.body)

    if data2["data"].first
      t = Time.parse( data2["data"].first["created_time"] )
      self.active_date = t
      self.save
      puts "User #{self.id} is active at #{t}"
    end

  end

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.status = "alive"
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end

    user.fb_token = auth[:credentials][:token]
    user.fb_expires_at = Time.at(auth[:credentials][:expires_at])
    user.save!
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = current_user
  end

  def update
    if current_user.update(set_user)
      if params[:from] == "signup"
        redirect_to new_contact_path
      else
        redirect_to messages_path
      end
    else
      redirect_to :back
    end
  end

  def set_user
    params.require(:user).permit(:name, :email, :address, :phone, :home_phone)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
  <div class="col-md-4 col-md-push-4">
    <h4 class="user_show">為了能確認您的近況，請盡可能完善您的個人資料</h4>

    <%= form_for @user, :url => update_profile_path do |f|%>

      <%#= hidden_field_tag "from", params[:from] %>

      <div class="form-group">
        <%= f.label "真實姓名" %> <br>
        <%= f.text_field :name, :value => @user.name, :class => "form-control"  %>
      </div>
      <div class="form-group">
        <%= f.label "行動電話" %> <br>
        <%= f.text_field :phone, :value => @user.phone, :class => "form-control"  %>
      </div>
      <div class="form-group">
        <%= f.label "室內電話" %> <br>
        <%= f.text_field :home_phone, :value => @user.home_phone, :class => "form-control"  %>
      </div>
      <div class="form-group">
      <%= f.label "Email" %> <br>
      <%= f.text_field :email, :value => @user.email, :type => "email", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "地址" %> <br>
        <%= f.text_field :address, :value => @user.address, :class => "form-control"  %>
      </div>

      <%= f.submit "更新個人資料", :class => "btn btn-primary pull-right" %>
    <% end %>

  </div>