config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
  end

  get "/profile" => "users#show", :as => "profile"
  patch "/profile" => "users#update", :as => "update_profile"

  get "/ask_alives" => "ask_alives#confirm", :as => "ask_alive"

  get "/admin" => "ask_alives#ask_admin", :as => "admin"
  get "/admin/check_facebook" => "ask_alives#check_facebook", :as => "check_facebook"
  get "/admin/send_theword" => "ask_alives#send_theword", :as => "send_theword"
  get "/admin/send_ask_mail" => "ask_alives#send_ask_mail", :as => "send_ask_mail"

  root 'messages#index'

  resources :messages
  resources :contacts

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>theWord 遺言保管服務</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <%= favicon_link_tag 'public/bentobanto.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "theWord 微遺言", messages_path, :class => "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">

    <ul class="nav navbar-nav navbar-right">

      <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag current_user.image, :height => "100%", :width => "auto" %>
          <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to('修改個人資料', profile_path) %></li>
              <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      <% end %>

    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

<%= yield %>

</body>

</html>